name: Feature
description: 新機能や改善提案
title: "[Feature] "
body:
  - type: markdown
    attributes:
      value: |
        機能提案ありがとうございます。背景と価値が分かるように記載してください。
        実装PRでは、関連Issueがある場合に `Refs #<issue番号>` または `Closes #<issue番号>` を記載してください。

  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
      description: 現状の困りごとや制約
      placeholder: 例) 〜が手作業で、毎回時間がかかる
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 提案内容
      description: どんな仕様・挙動が望ましいか
      placeholder: 例) 〜の画面に一括更新ボタンを追加する
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 対象範囲
      description: 対象と非対象を明確にしてください
      placeholder: 例) 対象: ダッシュボード画面 / 非対象: API仕様変更
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 検討した代替案
      description: 必要に応じて記載してください

  - type: textarea
    id: acceptance
    attributes:
      label: 完了条件
      description: このIssueが完了したと判断できる条件
      placeholder: |
        - [ ] 条件1
        - [ ] 条件2
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: 想定効果
      description: どのユーザーにどのような価値があるかを記載してください
      placeholder: 例) 作業時間を毎週30分削減できる

  - type: textarea
    id: notes
    attributes:
      label: 補足
      description: 参考リンク、モック、図など
